### ISSUE TITLE
Can't connect to wallet, showing 0.0 ETH after signing in ! 

### ISSUE THREAD

**Issue by Al-ImranRony** [shreyassai123/NFT-Wallet#2]
### **I'm facing an issue connecting my wallet by signing in, does NFT-Wallet provide importing wallet or only builtin wallet ?**

After going through all the steps for pod, firebase and infura api , I'm seeing 0.0 ETH and no sign of my wallet which holds 2  ETH on ropsten testnet.

Can you tell me the way around wallet connect approach, please  ?

**Comment by shreyassai123** [comment]
Could you send the necessary screenshots (the account page, and firestore's data field)?

**Comment by Al-ImranRony** [comment]
OK, I should’ve given the screenshots earlier . Here...

Account page :
![Account page](https://user-images.githubusercontent.com/32633579/154418090-1224d190-031f-423f-ab3a-a79aaac0ed65.PNG)

Firestore's data field: 
<img width="1141" alt="Screen Shot 2022-02-17 at 12 05 57 PM" src="https://user-images.githubusercontent.com/32633579/154418214-41f622ce-f485-4382-9f90-9454e842a4e7.png">

Project console showing successful login:
<img width="1149" alt="Screen Shot 2022-02-17 at 12 20 47 PM" src="https://user-images.githubusercontent.com/32633579/154418308-4a52bd59-6e61-4903-b66a-2fc33efa73ba.png">

**Comment by shreyassai123** [comment]
Is the uid given there the same as your account's uid? (To check this, go the authentication menu). Could you also verify again if the private key and the public key are correct?

**Comment by Al-ImranRony** [comment]
Thanks for reaching out @shreyassai123 
The uid is correct but publicKey and private key aren’t  ! 

1. Should I edit the public key on on firestore ? 
2. and where should the private key set up ?
